services:
  db:
    container_name: linkchain_pgvector
    image: ankane/pgvector
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vectordb
    volumes:
      - linkchain_pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"


  api:
    container_name: linkchain_api
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ../src:/app
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=vectordb
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432

volumes:
  linkchain_pgdata:
